mappings:
  GoogleAnalyticsConfigExtension: SilverStripers\GoogleAnalytics\GoogleAnalyticsConfigExtension
  GoogleAnalyticsControllerExtension: SilverStripers\GoogleAnalytics\GoogleAnalyticsControllerExtension
  GoogleTrackEvent: SilverStripers\GoogleAnalytics\GoogleTrackEvent
