mappings:
  GoogleAnalyticsConfigExtension: Silverstripers\GoogleAnalytics\extensions\GoogleAnalyticsConfigExtension
  GoogleAnalyticsControllerExtension: Silverstripers\GoogleAnalytics\extensions\GoogleAnalyticsControllerExtension
  GoogleTrackEvent: Silverstripers\GoogleAnalytics\models\GoogleTrackEvent
