---
Name: googleanalytics
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverStripers\GoogleAnalytics\GoogleAnalyticsConfigExtension
SilverStripe\Control\Controller:
  extensions:
    - SilverStripers\GoogleAnalytics\GoogleAnalyticsControllerExtension
