---
Name: googleanalytics
After: 'framework/*','cms/*'
---
SiteConfig:
  extensions:
    - SilverStripers\GoogleAnalytics\GoogleAnalyticsConfigExtension
Controller:
  extensions:
    - SilverStripers\GoogleAnalytics\GoogleAnalyticsControllerExtension
